# modify header dict to change names of each col
# modify default_cols list to modify columns shown by default
#   - entries should be a key from the headers dict
#   - columns are shown in same order they appear (except for year / link / thread, which have a predefined position for formatting reasons)

# ____ Cog settings ____

# gives #S123 / MM-YY
date_template: |-
  {% set yr = '%02d'|format(DATE[0]) %}
  #({{TYPE[0].upper()}}){{'%02d'|format(DATE[1])}}-{{yr}}

# header names for the equip tables --- see command settings to customize which cols are actually used by default
equip_headers:
  date: "# Date"
  price: Price
  quantity: Units
  unit_price: PPU
  seller: Seller
  buyer: Buyer
  name: Item Name

# headers for the summary tables
summary_headers:
    #col headers
    category: Category
    total_count: Count
    total_credits: Credits
    unknown: ??

    # row headers
    total: ">Total<"

# equip names containing at least one value in list as substring will be chucked in that group
summary_groups:
  1H: [axe, club, rapier, shortsword, wakizashi]
  2H: [estoc, longsword, mace, katana]
  Staff: [oak, redwood, willow, katalox]
  Shield: [buckler, kite, force]
  Cloth: [cotton, phase]
  Light: [leather, leather]
  Heavy: [plate, power]


# ____ Command settings ____

item:
  default_cols: [quantity, price, unit_price, buyer, seller, date]
  stat_col_width: 40
  page_limit_server: 3
  page_limit_dm: 15
  min_search_length: 3



# ____ Do-not-modify section ____

# keywords in query --> keys in data dict
# helps determine which columns are needed in table printout
key_map:
  time: date
  name: name
  seller: seller
  buyer: buyer
  maxq: quantity
  minq: quantity
  maxp: price
  minp: price
  maxu: unit_price
  minu: unit_price
  date: date