omit_template: |-
  {% set nl = "\n" if HAS_LINK else "" %}
  {% set om = PAGES|length - PAGE_LIMIT %}
  {% set pg = "pages" if om > 0 else "page" %}
  {% if GIST_LINK %}
  {{nl}}{{om}} {{pg}} omitted. Please see <{{GIST_LINK}}> for the full printout.
  {% else %}
  {{nl}}{{om}} {{pg}} omitted. Please DM for the full printout.
  {% endif %}
